# Generated by Django 3.2.9 on 2021-12-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_hotel_type'),
        ('payments', '0003_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotels.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment',
            field=models.CharField(choices=[('credit_card', 'Credit card'), ('virtual_account', 'Virtual account'), ('transfer_account', 'Transfer account'), ('phone', 'Phone'), ('toss', 'TOSS'), ('kakaopay', 'KAKAOPAY'), ('naverpay', 'NAVERPAY'), ('payco', 'PAYCO')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
