<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-12-09 16:17
=======
# Generated by Django 3.2.9 on 2021-12-05 18:37
>>>>>>> d07ec9aa931c2682d2285718f5fc9398fc8e0807

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='', max_length=50)),
<<<<<<< HEAD
                ('price', models.CharField(default='', max_length=50)),
=======
                ('price', models.IntegerField(default=0)),
>>>>>>> d07ec9aa931c2682d2285718f5fc9398fc8e0807
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
        ),
    ]
