# Generated by Django 3.2.9 on 2021-12-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
