# Generated by Django 3.2.9 on 2021-12-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_post_mainphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_product',
            fields=[
                ('pro_seq', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=255)),
                ('start_dt', models.DateTimeField(verbose_name='date published')),
                ('end_dt', models.DateTimeField(verbose_name='date published')),
                ('reg_dt', models.DateTimeField(auto_now_add=True)),
                ('reg_id', models.CharField(max_length=50)),
                ('thumb_file', models.ImageField(upload_to='')),
                ('reserve_yn', models.CharField(max_length=1)),
                ('del_yn', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='mainphoto',
        ),
    ]
