# Generated by Django 3.2.9 on 2021-12-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20211205_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='thumb_file',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_thumb/%Y/%m/%d'),
        ),
    ]
