# Generated by Django 3.2.9 on 2021-12-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20211202_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_product',
            name='del_yn',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='tb_product',
            name='reg_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tb_product',
            name='reserve_yn',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='tb_product',
            name='thumb_file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
