# Generated by Django 3.2.9 on 2021-12-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_hotel_thumb_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='hotels.RoomType'),
        ),
    ]
