# Generated by Django 3.2.9 on 2021-12-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20211202_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_product',
            name='pro_seq',
        ),
        migrations.AddField(
            model_name='tb_product',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
