# Generated by Django 3.2.9 on 2021-11-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mobile',
            new_name='user_phone',
        ),
    ]
