# Generated by Django 3.2.9 on 2021-12-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('request', models.TextField()),
                ('payment', models.CharField(choices=[('credit_card', 'Credit card'), ('virtual_account', 'Virtual account'), ('transfer_account', 'Transfer account'), ('phone', 'Phone'), ('toss', 'TOSS'), ('kakaopay', 'KAKAOPAY'), ('naverpay', 'NAVERPAY'), ('payco', 'PAYCO')], max_length=200)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotels.hotel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
