<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-12-09 16:17
=======
# Generated by Django 3.2.9 on 2021-12-05 18:37
>>>>>>> d07ec9aa931c2682d2285718f5fc9398fc8e0807

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
            ],
            options={
                'verbose_name': 'Booked Day',
                'verbose_name_plural': 'Booked Days',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('request', models.TextField()),
                ('payment', models.CharField(choices=[('credit_card', 'Credit card'), ('virtual_account', 'Virtual account'), ('transfer_account', 'Transfer account'), ('phone', 'Phone'), ('toss', 'TOSS'), ('kakaopay', 'KAKAOPAY'), ('naverpay', 'NAVERPAY'), ('payco', 'PAYCO')], max_length=200)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotels.hotel')),
=======
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=12)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
>>>>>>> d07ec9aa931c2682d2285718f5fc9398fc8e0807
            ],
            options={
                'abstract': False,
            },
        ),
    ]
