<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-12-09 16:17
=======
# Generated by Django 3.2.9 on 2021-12-05 18:37
>>>>>>> d07ec9aa931c2682d2285718f5fc9398fc8e0807

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rooms.room'),
        ),
    ]
