# Generated by Django 3.2.9 on 2021-12-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_hotel_type'),
        ('reservations', '0004_auto_20211205_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotels.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='request',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
