# Generated by Django 3.2.9 on 2021-12-09 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20211206_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment',
            field=models.CharField(choices=[('credit_card', 'Credit card'), ('virtual_account', 'Virtual account'), ('transfer_account', 'Transfer account'), ('phone', 'Phone'), ('toss', 'TOSS'), ('kakaopay', 'KAKAOPAY'), ('naverpay', 'NAVERPAY'), ('payco', 'PAYCO')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookedDay',
        ),
    ]
